# Package Overview
package_name: housing_model

# Data Files
training_data_file: housing_dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: SalePrice

pipeline_name: housing_model
pipeline_save_file: housing__model_output_v

features:
  - MSSubClass
  - MSZoning
  - LotFrontage
  - LotArea
  - Street
  - Alley
  - LotShape
  - LandContour
  - Utilities
  - LotConfig
  - LandSlope
  - Neighborhood
  - Condition1
  - Condition2
  - BldgType
  - HouseStyle
  - OverallQual
  - OverallCond
  - YearBuilt
  - YearRemodAdd
  - RoofStyle
  - RoofMatl
  - Exterior1st
  - Exterior2nd
  - MasVnrType
  - MasVnrArea
  - ExterQual
  - ExterCond
  - Foundation
  - BsmtQual
  - BsmtCond
  - BsmtExposure
  - BsmtFinType1
  - BsmtFinSF1
  - BsmtFinType2
  - BsmtFinSF2
  - BsmtUnfSF
  - TotalBsmtSF
  - Heating
  - HeatingQC
  - CentralAir
  - Electrical
  - FirstFlrSF
  - SecondFlrSF
  - LowQualFinSF
  - GrLivArea
  - BsmtFullBath
  - BsmtHalfBath
  - FullBath
  - HalfBath
  - BedroomAbvGr
  - KitchenAbvGr
  - KitchenQual
  - TotRmsAbvGrd
  - Functional
  - Fireplaces
  - FireplaceQu
  - GarageType
  - GarageYrBlt
  - GarageFinish
  - GarageCars
  - GarageArea
  - GarageQual
  - GarageCond
  - PavedDrive
  - WoodDeckSF
  - OpenPorchSF
  - EnclosedPorch
  - ThirdSsnPorch
  - ScreenPorch
  - PoolArea
  - PoolQC
  - Fence
  - MiscFeature
  - MiscVal
  - MoSold
  - YrSold
  - SaleType
  - SaleCondition
    # generated from name          <--Before pipeline alongwith loading the data


unused_fields:  # Features to drop before pipeline
  - Id
# Features inside processing pipeline
vars_dates:
  - YearBuilt
  - YearRemodAdd
  - GarageYrBlt

vars_cat:
- MSZoning
- Street
- Alley
- LotShape
- LandContour
- Utilities
- LotConfig
- LandSlope
- Neighborhood
- Condition1
- Condition2
- BldgType
- HouseStyle
- RoofStyle
- RoofMatl
- Exterior1st
- Exterior2nd
- MasVnrType
- ExterQual
- ExterCond
- Foundation
- BsmtQual
- BsmtCond
- BsmtExposure
- BsmtFinType1
- BsmtFinType2
- Heating
- HeatingQC
- CentralAir
- Electrical
- KitchenQual
- Functional
- FireplaceQu
- GarageType
- GarageFinish
- GarageQual
- GarageCond
- PavedDrive
- PoolQC
- Fence
- MiscFeature
- SaleType
- SaleCondition

vars_num:
- MSSubClass
- LotFrontage
- LotArea
- OverallQual
- OverallCond
- MasVnrArea
- BsmtFinSF1
- BsmtFinSF2
- BsmtUnfSF
- TotalBsmtSF
- FirstFlrSF
- SecondFlrSF
- LowQualFinSF
- GrLivArea
- BsmtFullBath
- BsmtHalfBath
- FullBath
- HalfBath
- BedroomAbvGr
- KitchenAbvGr
- TotRmsAbvGrd
- Fireplaces
- GarageCars
- GarageArea
- WoodDeckSF
- OpenPorchSF
- EnclosedPorch
- ThirdSsnPorch
- ScreenPorch
- PoolArea
- MiscVal
- MoSold
- YrSold




  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

